services:
  app:
    image: agungdh/ate_ngambek:latest
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .env:/var/www/html/.env
  worker:
    image: agungdh/ate_ngambek:latest
    restart: always
    volumes:
      - .env:/var/www/html/.env
    command: ["php", "/var/www/html/artisan", "queue:work", "--sleep=3", "--tries=3"]
