services:
  app:
    image: agungdh/ate_ngambek:latest
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .env:/var/www/html/.env
  worker:
    image: agungdh/ate_ngambek:latest
    restart: always
    volumes:
      - .env:/var/www/html/.env
    command:
      - sh
      - -lc
      - |
        php artisan optimize
        exec php artisan queue:work --sleep=3 --tries=3 --no-interaction
  scheduler:
    image: agungdh/ate_ngambek:latest
    restart: always
    volumes:
      - .env:/var/www/html/.env
    command:
      - sh
      - -lc
      - |
        php artisan optimize
        exec php artisan schedule:work --no-interaction
