services:
  adminer:
    image: adminer
    restart: always
    environment:
        TZ: Asia/Jakarta
    ports:
      - "127.0.0.1:8083:8080"
  postgres:
    image: postgres:17
    container_name: postgres_db
    restart: always
    environment:
      TZ: Asia/Jakarta
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ate_ngambek
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
